instances/templates/instances.html
When user (not superuser) opens `Console` at instances, 500 error occured.
So, I fixed `onclick` of `Console` link.
=> Fix open_console at instances

instances/views.py, vrtManager/create.py, vrtManager/util.py
Instead of creating instance with no password, created them with a generated password. The password is readable in vncsettings.
This is another  way to fix #95
=> Create instances with a random generated vnc password by default

storages/templates/create_stg_block.html
Javascript is complaining about the escaped underscore in the form input required pattern. A console error occurs in both chrome and firefox. Chrome seems to not allow the input at all. Seen on OSX.
Fixing for "iso path" and "lvm name".
=> Fixing add storage regex issue on 'iso path' and 'lvm name'

instances/views.py
in the function `get_snapshot`，it return a list of dict, such as:
```
[
{'date':'', 'name': ''},
{'date':'', 'name': ''},
]
```
it raise an Exception `sorted` not supported between instances of 'dict' and 'dict'.
=> fix:sorted btween 'dict' and 'dict'

dev/libvirt-bootstrap.sh, instances/templates/instance.html, instances/views.py, storages/templates/create_stg_vol_block.html, storages/templates/storage.html, storages/views.py, vrtManager/storage.py
Hi retspen,
with this pull:
1. I fixed resembling clone/add volume extension 
2. I fixed qcow volume creation
3. I merge honza's staff user permissions
4. Readme: add epel-release and libguestfs-tools for centos installation
thanks
=> Fix and Addition

instances/views.py
host_is_up function returns either True or err-like object, so we can't compare status with any object. Instead comparison should be made against True.
=> Fix bug with err instead of True in connection_manager.host_is_up, which lead to freeze in panel if compute is down

computes/templates/computes.html
When a compute can not be connected (for whatever reason) mark it as
not connected in the template.
The generic check
if compute.status
is not enough because the status variable can contain a string with a
connection error.
=> Mark the unreachable computes properly

computes/templates/computes.html, console/templates/console-vnc-full.html, create/views.py, instances/templates/add_instance_volume.html, instances/templates/edit_instance_volume.html, instances/templates/instance.html, instances/views.py, networks/templates/add_network_qos.html, vrtManager/connection.py, vrtManager/create.py, vrtManager/instance.py, webvirtcloud/settings.py.template
Hi retspen,
There are a lot changes:
1. Edit instance disk capability is added.
2. Add new disk options for instance disk.
3. Instance network tab rearranged to show ipv6 and ipv4 addresses.
4. Show instance network driver model/change capability
5. Some bugs, typo and minor improvements like notification.
thanks
=> New additions, changes

appsettings/admin.py, appsettings/context_processors.py, appsettings/middleware.py, appsettings/settings.py, instances/templates/instance.html, webvirtcloud/settings.py.template
Note that settings.py now require `'appsettings.middleware.AppSettingsMiddleware',` and `'appsettings.context_processors.app_settings',` in `MIDDLEWARE` and `context_processors` respectively.
=> Some improvements for appsettings app

console/views.py
When VM has no console available, `console_type` will be None and there'll be exceptions.
=> Handle None console type

console/novncd
Revert accidentally change variable for novncd port configuration.
Change variable `WS_PUBLIC_PORT` back to `WS_PORT`
=> Fix Port configuration for novncd

conf/requirements.txt
Looks like libvirt-python 6.8.0 has some weird bug which causes `NameError: name 'dom' is not defined` on trying to snapshot instance. Downgrading to 6.7.0 fixes the issue.
=> Downgrade libvirt-python to fix taking snapshots

.github/workflows/codeql-analysis.yml, .github/workflows/linter.yml
Superlinter fixes.
Add security analysis.
=> Code security analysis & superlinter

README.md, conf/supervisor/gstfsd.conf, dev/libvirt-bootstrap.sh, instances/views.py, webvirtcloud.sh
Centos 8 host bootstrap script fixed. 
there is no more --listen parameter but only libvirtd-tcp or libvirtd-tls services exist for running daemon mode.
clck.ru -> bit.ly conversion is made, because wget/curl does not accept theirs algorithm and halts.
snapshot related some small bugs are fixed
=> script fixes etc

console/templates/console-base.html, instances/templates/instances/settings_tab.html, static/js/novnc/app/styles/base.css, static/js/novnc/app/styles/lite.css, storages/templates/storage.html, storages/views.py, templates/navbar.html, templates/pleasewaitdialog.html
sticky top for navbars
fix storage clone error
fix please wait modal
=> fixes somethings

README.md, admin/migrations/0003_create_group_technicians.py, console/views.py, instances/models.py, instances/templates/allinstances.html, instances/templates/allinstances_index_grouped.html, instances/templates/allinstances_index_nongrouped.html, instances/templates/instance.html, instances/views.py, webvirtcloud/.dec_ldap_pwd.sh, webvirtcloud/ldapbackend.py, webvirtcloud/settings.py.template
Hi,
There are some additions :
**1) Added permission to see all instances**
The goal is to be able to give the right to a user in a group to see all the instances.
**2) Added Technicians group**
The goal is to be able to automatically add users from the LDAP directory to the Technicians group based on the cn and to assign specific permissions afterwards.
**3) Automatic input first name last name and email with ldap**
The goal is to add automatically the last name, the first name and the email when creating a user from the LDAP directory.
**4) Added DRBD status**
My infrastructure is composed of a cluster of 2 nodes with a DRBD to replicate the storage. So I added the retrieval of the role and state of the disks in webvirtcloud by ssh.
**5) Added ldap password encryption**
The goal was to …
=> New additions

accounts/utils.py, webvirtcloud/settings.py.template
fix ssh-key verification problem because of decodestring depreciation.
and fix settings.py.template redundant module error.
=> fix setting.py.template & decodestring convert

storages/api/viewsets.py, storages/forms.py, vrtManager/instance.py
Please review the storages/forms.py file that contains the major changes, and the rest of the files are only optimized for code structure.
Valid linux folder paths:
/home/regan/my_vm
/home/regan/my-vm
/home/regan/_my-vm
Signed-off-by: herengui <herengui@uniontech.com>
=> The storage pool path should be allowed to contain '-' and '_'

storages/forms.py
Matching twice is optimized to matching once
=> enhancement: optimize regular expressions

admin/views.py, instances/utils.py
This is done to automatically create the UserAttributes object in case LDAP User Backend didn't create it.
fixes #602
=> Get UserAttributes object using get_or_create

storages/templates/storage.html
ifequal and ifnotequal are deprecated in Django 4.0
Fixes #604
=> Replace ifnotequal with if

instances/utils.py, vrtManager/util.py, webvirtcloud/settings.py.template
Removed the hard coded MAC OUI in the code and instead fetches the OUI from settings.py
If independent instances of WebVirtCloud (or any libvirt) exists on the same subnet and VMs are configured to use a bridge interface, this could lead to duplicate MACs on the same subnet (low probability, but still possible).
This change gives the user a choice to define an OUI.
=> Get MAC OUI from settings.py

conf/nginx/webvirtcloud.conf
Fix for issue #577 as I don't see the fix from #440 working at all.
Since noVNC Full sets the path to "websockify", workaround is to added a Location for it in the nginx configuration
=> nginx conf - Fix for issue #577

webvirtcloud.sh
This (simple) patch fixes issue#614 where the Quick Install script overrides nginx upstream wssocketiod port.
=> Fixes Quick Install overrides nginx upstream wssocketiod

conf/nginx/webvirtcloud.conf
According to the specification of [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), the value shall match the used protocol (e.g., "http", "https") which is provided as scheme variable in nginx.
=> Fixed nginx X-Forwarded-Proto to match the protocol ("http", "https")

webvirtcloud.sh
The installation script wasn't accepting the default from `hostname --fqdn` that was being displayed in the question.
This change uses `hostname --fqdn` if the user just hits enter.
=> Install script accepts default hostname

conf/requirements.txt, instances/views.py
The old code could not run on Python-3.13 because crypt stdlib was dropped. I try to use crypt-r to replace it and works on Python-3.13 in Debian trixie/sid. So I commit the changes and open a pull request. Hope it will be merged. Thanks.
=> crypt-r replaces crypt stdlib, support python-3.13
