instances/templates/instances.html
=> Remove double "Add new instance" button

instances/views.py
When signed in user (not superuser), show only instances added for that user.
=> Show only UserInstances at instances

computes/templates/overview.html
Correction of the display of information on architecture and memory
=> Fix Compute Overview

README.md
If you create venv before moving the directory, you get symlinking issues
=> Symlink issues with venv

instances/views.py
Add support get .vv file for external application (virt-viewer)
=> Add support get .vv file

vrtManager/instance.py
dependency for https://github.com/retspen/webvirtcloud/pull/50
=> dependency for #50

Dockerfile, conf/runit/nginx, conf/runit/nginx-log-forwarder, conf/runit/novncd.sh, conf/runit/webvirtcloud.sh
```bash
sudo docker build -t webvirtcloud .
sudo docker run -d -p 80:80 -p 6080:6080 webvirtcloud
```
Instant start webvirtcloud :smile: 
Or `sudo docker run -d -p 80:80 -p 6080:6080 jcppkkk/docker-webvirtcloud` for quick test
=> Dockerization

webvirtcloud/urls.py
In my scenario, my storage server is NFS server but the path It has hierarchical names. In this case, I need change urls.py for to list storage path in compute node.
=> adjust path to storage for url.

accounts/templatetags/tags_fingerprint.py, create/forms.py, create/templates/create_instance.html, create/views.py, instances/views.py, vrtManager/create.py, vrtManager/instance.py
Hi,
I port my recent pull request on WebVirtMgr (https://github.com/retspen/webvirtmgr/pull/608) to WebVirtCloud (improvement of console view come in another separated pull request #104).
=> Improve RBD support

console/templates/console-base.html, console/templates/console-spice.html, console/templates/console-vnc.html
Hi,
I port my recent pull request on WebVirtMgr (retspen/webvirtmgr#608) to WebVirtCloud (improvement of RBD/HDD Cache support come in another separated pull request #103).
=> Unified VNC/SPICE console interfaces with bootstrap

accounts/migrations/0004_userinstance_is_vnc.py, accounts/models.py, accounts/templates/account.html, accounts/views.py, instances/templates/instance.html, instances/views.py
We also correct a security bug: permission where not checked before resize or delete and just the web form were changed.
fix #107
=> Add an option to allow an user to change VNC settings

README.md, accounts/urls.py, conf/requirements.txt, instances/views.py, webvirtcloud/settings.py.template
@catborise forgot to change the Django version in the requirements, so that was the rpoblem with the login page not working. I've fixed this and also the non-loading instances page because of a miss-configured variable.
=> Fixing django version requirement and instances page not loading

instances/templates/add_instance_network_block.html, instances/templates/instance.html, instances/views.py, vrtManager/instance.py
hi,
* add new network for instance (modal)
* fix edit network. @catborise made some changes, which disabled functionality of shared interface direct naming. these changes are now enhanced with compute interfaces.
* minor fixes in html/js instance template
thanks
fous
=> add network for instance

README.md, instances/templates/instance.html, vrtManager/instance.py
hi,
* instance clone process now handles ceph/rbd images properly
* minor README changes
please merge
thanks
fous
=>  patch for cloning rbd images 

instances/templates/instance.html, instances/views.py, vrtManager/instance.py
hi,
* quotas for admins are not handled. it is not necessary, since admin can do everything :)
* update novncd script for runit (and readme)
* generating clone disk names revisited
please merge
thanks
fous
=> Clone revisited

instances/templates/allinstances_index_grouped.html
Fix "Error: Syntax error, unrecognized expression: [host=pc.local]"
=> Fix collapse on hostname with "."

create/templates/create_instance.html, create/views.py, dev/libvirt-bootstrap.sh, instances/templates/allinstances.html, storages/views.py, vrtManager/create.py
Hi retspen,
1. remove unnecessary comment lines
2. fix: refresh pool while getting volume list
3. libvirt-bootstrap.sh: host installation fix for ubuntu 18.04 
4. some typos
=> fix some glitches & update

computes/views.py, conf/requirements.txt, create/templates/create_instance.html, create/views.py, instances/templates/add_instance_volume.html, instances/templates/instance.html, instances/views.py, networks/templates/modify_fixed_address.html, networks/templates/network.html, networks/views.py, static/css/webvirtcloud.css, vrtManager/IPy.py, vrtManager/create.py, vrtManager/instance.py, vrtManager/network.py, vrtManager/util.py
Hi retspen,
I added some features:
1. Update requirements file
2. Add pool selection option while creating an instance with a template
3. Add cache info for instance disk list
4. Add Boot menu enable / disable function
5. Add Boot order change function(disk/cdrom/network)
6. Add titles for some buttons
7. Fix some bugs
8. Fix some typos
I hope you will accept.
Thanks.
=> Boot Menu/Order Functionality And some fixes

.travis.yml, conf/requirements.txt, instances/templates/add_instance_volume.html, instances/views.py, storages/templates/storage.html, templates/404.html, templates/500.html, templates/base.html, templates/errors_block.html, templates/messages_block.html, vrtManager/instance.py
Hi retspen,
i update and test new requirements. it is okey.
There are some bugs must be fixed. it is done.
some typo and translated strings.
thanks
=> Some fixes and updates 2

instances/views.py, interfaces/templates/interface.html, interfaces/views.py, networks/templates/modify_ipv4_fixed_address.html, networks/templates/modify_ipv6_fixed_address.html, networks/templates/network.html, networks/views.py, nwfilters/views.py, secrets/views.py, vrtManager/IPy.py, vrtManager/connection.py, vrtManager/instance.py, vrtManager/interface.py, vrtManager/network.py
Hi retspen,
i add ipv6 support for host network config. users can add/delete/modify static dhcp records for ipv6, also.
i add list of slaves which connected to the bridge.
some fixes and corrections
=> ipv6 support and bridge slave list & pep8 corrections

README.md, networks/templates/add_inbound_qos.html, networks/templates/add_outbound_qos.html, networks/templates/network.html, networks/views.py, vrtManager/network.py
Hi retspen,
- Add qos functions for network: Inbound & Outbound
=> Add Qos for Network Functions

dev/libvirt-bootstrap.sh, instances/templates/instance.html
Hi retspen,
debian10 changes package names. it added its support.
qos adding causes validation problem, i did fixed it.
ps: debian10 host does not work with novnc/spice console. i am researching but nothing find yet
=> Debian10 installation & And Qos fix

computes/templates/overview.html, dev/libvirt-bootstrap.sh, instances/templates/instance.html, instances/views.py, vrtManager/instance.py, webvirtcloud/settings.py.template
Hi retspen,
1. hotplug cpu enable disable.
2. Add/remove cpu while instance is running if hotplug cpu enabled.
3. Debian10 host config for qemu.conf rearranged.
thanks
=> add hot cpu enabling disabling functionality

instances/templates/instance.html, instances/views.py, interfaces/views.py, vrtManager/connection.py, vrtManager/instance.py, vrtManager/network.py
Hi retspen,
Some usesul new improvements;
1. Show Interface ip address with the help of guest agent.
2. Add link state for instance network. Without removing interface, it could be down or up.
3. Guest channel add remove.
4. Show if guest agent installed or not. Connected or not.
5. Fix some bugs with cdrom&q35, qemu&kvm type selection, host interface config error prevents instance editing. it is fixed also...
thanks.
=> Some improvements

computes/urls.py, manage.py
hi retspen,
there are some fixes.
thanks
=> some small fixes

console/templates/console-spice-full.html, console/templates/console-spice-lite.html
=> spice console password fix & translate additions

.github/workflows/linter.yml, Dockerfile, README.md, conf/nginx/webvirtcloud.conf, console/templates/console-spice-full.html, console/templates/console-spice-lite.html, console/templates/console-vnc-full.html, console/templates/console-vnc-lite.html, console/views.py, static/js/spice-html5/spice.css, webvirtcloud/settings.py.template
Hi retspen,
1. update docker image file and some minor additions
2. organize nginx to forward 6080 to 80 if user want to use reverse proxy.
3. add reverse proxy instruciton to readme
4. update console pages.
=> wsproxy patch

appsettings/migrations/0001_initial.py, appsettings/migrations/0003_auto_20200615_0637.py
fix for https://github.com/retspen/webvirtcloud/issues/356
=> edit choices field length

accounts/forms.py, accounts/models.py, accounts/templates/account.html, accounts/templates/accounts-list.html, accounts/templates/accounts.html, accounts/templates/accounts/change_password_form.html, accounts/templates/profile.html, accounts/tests.py, accounts/urls.py, accounts/utils.py, accounts/views.py, admin/templates/admin/user_list.html, appsettings/settings.py, conf/test-vm.xml, instances/models.py, instances/templates/add_instance_network_block.html, instances/templates/instances/settings_tab.html, instances/tests.py, templates/common/confirm_delete.html, templates/navbar.html
Added some improvements to accounts app and created tests. Accounts app test coverage is 98% overall coverage 55%.
=> Accounts app improvements and tests

accounts/apps.py, conf/test-vm.xml, instances/apps.py, instances/forms.py, instances/tests.py, instances/urls.py, instances/utils.py, instances/views.py
Instances app coverage is now at 86%, overall coverage is 62%.
There're also some code cleanup and minor bug fixes.
=> More instances tests

.github/workflows/linter.yml, console/views.py
console access security hardening..
=> security update

instances/templates/instance.html, instances/templates/instances/access_tab.html, instances/templates/instances/destroy_tab.html, instances/templates/instances/info_tab.html, instances/templates/instances/power_tab.html, instances/templates/instances/resize_tab.html, instances/templates/instances/settings_tab.html, instances/templates/instances/snapshots_tab.html, instances/templates/instances/stats_tab.html, instances/urls.py, instances/views.py, networks/templates/network.html, vrtManager/instance.py
get os info with qemu-guest-agent. show them on info tab
=> Add guest info(hostname,os,version,kernel) tab. indendation fixes

computes/utils.py, instances/utils.py
=> fix uuid and name changes and update them on db correctly.

computes/utils.py, conf/requirements.txt, dev/requirements.txt, instances/utils.py
=> update python packages

instances/models.py, instances/templates/add_instance_network_block.html, instances/templates/instances/settings_tab.html, instances/views.py, interfaces/views.py, vrtManager/connection.py, vrtManager/instance.py, vrtManager/interface.py
There is a bug with related instance network change. if user want to change interface from bridge to defined libvirt network, it was causes error. it is fixed
=> instance network change

webvirtcloud.sh
Signed-off-by: wangqing <wangqing@uniontech.com>
=> webvirtcloud.sh support rockylinux

conf/nginx/uos_nginx.conf, webvirtcloud.sh
Signed-off-by: herengui <herengui@uniontech.com>
=> add support uos

conf/nginx/openEuler_nginx.conf, webvirtcloud.sh
Signed-off-by: Lv Genggeng <lvgenggeng@uniontech.com>
=> add support openEuler

conf/nginx/uos_eagle_nginx.conf, webvirtcloud.sh
UOS is not a specific os, but a series of different OS, they use either dnf or apt package manager
At present, UOS has two systems, which are similar to fedora and debian, so they need to be adapted for two different codenames.
=> Enhanced system support

webvirtcloud.sh
=> add alma linux for know distributions

conf/daemon/consolecallback, conf/nginx/webvirtcloud.conf, conf/requirements.txt, conf/supervisor/webvirtcloud.conf, console/socketiod, console/templates/console-xterm.html, console/views.py, vrtManager/instance.py, webvirtcloud.sh, webvirtcloud/settings.py.template
Hello,
As libvirt can manage VNC or Spice Graphical Console, Libvirt also permit to have a serial console. They can be accessed using virsh console from libvirt libs.
I've try to implement them on WebVirtuCloud using an another WebSocket and XTerm librairy.
=> Implement Libvirt Serial Console as Console on WebVirtCloud

dev/libvirt-bootstrap.sh, gunicorn.conf.py, vrtManager/IPy.py, vrtManager/create.py, vrtManager/hostdetails.py, vrtManager/interface.py, vrtManager/network.py, vrtManager/nwfilters.py, vrtManager/storage.py, vrtManager/util.py, webvirtcloud/common_tags.py, webvirtcloud/ldapbackend.py
For shell:
- modify some shell scripts to make variable references safer
- remove useless local variables
- check exit code directly with 'if ! mycmd;'
For python:
- simplify comparison to boolean
- replace if statement with if expression
- use `contextlib`'s `suppress` method to silence an error
- convert for loop into list comprehension
- replace identity comprehension with call to collection constructor
- replace multiple comparisons of same variable with `in` operator
- use `except Exception:` rather than bare `except:`
- swap if/else branches, Remove unnecessary else after guard condition
- reduce cyclomatic complexity
- don't assign to builtin variable or keyword
=> Reduce code complexity

webvirtcloud/settings.py.template
=> fix syntax error while import settings.py

accounts/apps.py, accounts/views.py, admin/views.py, computes/api/serializers.py, computes/api/viewsets.py, computes/utils.py, computes/views.py, datasource/views.py, instances/api/serializers.py, instances/api/viewsets.py, instances/forms.py, instances/models.py, instances/views.py, interfaces/forms.py, interfaces/views.py, networks/api/serializers.py, networks/api/viewsets.py, networks/forms.py, networks/views.py, storages/api/viewsets.py, storages/models.py, storages/views.py, virtsecrets/views.py, vrtManager/create.py, vrtManager/instance.py, vrtManager/interface.py, vrtManager/storage.py
code format with black
eliminate code redundancy
=> code black format

console/novncd, console/socketiod, webvirtcloud/wsgi.py
When I was testing, I found that multiple zombie processes were generated, so I tried to fix it.
=> fix zombie processes

accounts/templates/logout.html, templates/403.html, templates/404.html
The template "base_auth.html" doesn't exist. It should be "base.html" which makes it similar to templates/500.html
=> Fix base templates

conf/systemd/README.md, conf/systemd/install.sh, conf/systemd/webvirt, conf/systemd/webvirt-cloud.service, conf/systemd/webvirt-gstfsd.service, conf/systemd/webvirt-novncd.service, conf/systemd/webvirt-socketiod.service
I've installed this application bare on ubuntu 22.04 and wanted to contribute my service files for other people that'd like to go that route.
Cheers
=> Ubuntu Service files

vrtManager/instance.py, vrtManager/storage.py
do not confuse a network volume with a network interface
=> Some fixes regarding Ceph/RBD volumes handling
